---
title: "Lab 1 Reflection"
description: ""
author: "Quinn Miyamoto"
date: "9/1/25"
categories:
  - reflection
draft: false
---

The blog on your Quarto portfolio is a space for you to write weekly reflections on what you’re learning in MicroPs. The list below is a non-exhaustive list of ideas of things you could write about if you’re struggling to come up with ideas.

What is something interesting you learned recently in lab or lecture?
How do you feel like the course is helping you to grow as a person? Reflect on the character traits you listed at the beginning of the course for ideas about specific areas of growth to reflect on.
What did you think about a recent AI prototype? How did your use of AI shape your thinking about what role these tools might play in the future of digital hardware design?
Search the Internet for a recent article related to embedded systems. Reflect on those systems through the lens of what you’re learning in MicroPs.
What are some ideas you’re thinking about exploring in your project and why?